import Head from "next/head";
import React from "react";
import { ReactNode } from "react";
import BigNav from "./BigNav";
import Footer from "./Footer";
import SmallNav from "./SmallNav";
import Subscribe from "./SubScribe";

type LayoutType = {
  title?: string;
  children: ReactNode;
};
const Layout = ({
  children,
  title = "Nest - Multipurpose eCommerce",
}: LayoutType) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BigNav />
      {children}
      <Subscribe />
      <Footer />
    </>
  );
};

export default Layout;
